# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-ci:
    name: Frontend CI Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AssignmentFrontend

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: AssignmentFrontend/package-lock.json
      - name: "Install Dependencies"
        run: npm ci
      - name: "Run Build"
        run: npm run build --if-present
      - name: "Run Test"
        run: npm run test

  backend-ci:
    name: Backend CI Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AssignmentAPI
  
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: AssignmentAPI/package-lock.json
      - name: "Install Dependencies"
        run: npm ci
      - name: "Run Build"
        run: npm run build --if-present
      - name: "Run Test"
        run: npm run test
